### ISSUE TITLE
Asset Reference dialog only shows images

### ISSUE THREAD

**Issue by johnfmorton** [selvinortiz/craft-plugin-doxter#11]
In a Doxter field, clicking the _Asset Reference_ button brings up a dialog box for your uploaded assets. It currently only shows uploaded image assets though, leaving out other files type from the list. For example, I have a _"samplefiles.zip"_ I'd like to reference in my body copy but can't use an asset reference to do that.

**Comment by selvinortiz** [comment]
@johnfmorton The latest release https://github.com/selvinortiz/craft-plugin-doxter/releases/tag/3.1.4 should address this issue. `composer update` away and let me know if I missed something.
