### ISSUE TITLE
Entries without an entry URI format cause exception

### ISSUE THREAD

**Issue by bossanova808** [selvinortiz/craft-plugin-doxter#12]
If an entry without a uri format is used like this `{{ note.markdown|doxter }}` then one gets an exception:

<pre>Exception &#039;TypeError&#039; with message &#039;Return value of craft\services\Elements::_getRefTokenReplacement() must be of the type string, null returned&#039; 

in /var/www/vhosts/notes/vendor/craftcms/cms/src/services/Elements.php:1426
</pre>

(just thought I'd put this here so it doesn't get lost to Slack's tiny history!)

**Comment by selvinortiz** [comment]
@bossanova808 Thank you, Jeremy. I'll look into this as I prepare the plugin for the latest RC.
