### ISSUE TITLE
Doxter-field content only showing up after interaction

### ISSUE THREAD

**Issue by LukasKnuth** [selvinortiz/craft-plugin-doxter#14]
I'm using the Doxter-field from the plugin in my main content-Matrix. It works great and saves correctly.

But: When I go to edit an article, all Doxter-fields are empty. They also show an empty scroll-bar on the right. As soon as I interact with a field (click it for example), it's content shows up as expected and the scroll-bar is gone. I have to do that for each individual field though!

Versions:

* Doxter: 3.1.5
* CraftCMS: 3.0.0-RC16.1
* Chromium: 65.0.3325.181
* FireFox: 59.0.2

I can't see any errors in the browser console, except for this message (multiple times): 

    Double-instantiating a menu button on an element

The log says it's from `garnish.js:220`, not sure if it's related.

**Comment by LukasKnuth** [comment]
For completions sake, I updated to the newest Craft 3.0.0-RC17.1 and deleted and re-created everything in `web/cpressources` (because I was getting other JS errors after the update).

The problem remains. If any more information is needed, feel free to ask!

**Comment by LukasKnuth** [comment]
Okay, I did some digging:

- The issue seems to only occur, if the field is not on the first tab of an entry-type
- It seems to be an issue with the editor-library SimpleMDE: https://github.com/sparksuite/simplemde-markdown-editor/issues/596

I'm going to investigate this further and get back with any findings.

**Comment by LukasKnuth** [comment]
I can confirm that the solution proposed in the above bug report fixes the issue. However, sadly there is no nice or build-in way to tell if the tabs on the editor have changed:

* New tabs always change the hash in the URL-bar. There is the `hashchange`-event on the `window`-object, but that doesn't really work in all browsers
* AFAIK, the tabs are created with jQuery UI which exposes an `tabactivated`-event on the navigation-element. This however is not fired.
* A very simple working solution is to listen for `click`-events on the navigation-element.

All the above solutions _could_ easily be broken by a Craft update. The "best" way to handle this would be, if the Craft JS code would fire an event when the tabs are changed.

Any advice on what you would accept as a PR @selvinortiz or @gui-gui ?

**Comment by selvinortiz** [comment]
@LukasKnuth I really appreciate you digging into this. Would love a PR that you feel good about. Put something together and we'll review it.

**Comment by LukasKnuth** [comment]
Okay, so I did some more digging:

* The JS method in Craft that actually handles switching tabs is located in [`CP.js:250`](https://github.com/craftcms/cms/blob/00a15b871a44af112662a1c7f06632bfe3c8a016/src/web/assets/cp/src/js/CP.js#L250)
* This function manually triggers the `resize` and `scroll`-events on `window` and `document` respectively
  * The `resize`-element also triggers, when the browser-window is resized. Probably wouldn't be a problem but who knows
  * The `scroll`-element could potentially be triggered very often, although for some reason it doesn't trigger when I scroll on the page. **But**: The comment right above it says, that this is a fix for Redactor, which is no longer part of the base system with Craft 3. Who knows how long this will exist there... 
* CodeMirror (what SimpleMDE uses under the hood), [already listens to the windows `resize`-event](https://github.com/codemirror/CodeMirror/blob/9ec124580735235063c59a8d781ed6e6e498b031/src/edit/global_events.js#L23), and it works correctly when you resize the window but not when switching tabs.
* Looking at the [source of jQuery](https://github.com/jquery/jquery/blob/73d7e6259c63ac45f42c6593da8c2796c6ce9281/src/event.js#L108), it looks like it's implementation of `on` and `trigger` doesn't use the `addEventListener`-API that [CodeMirror uses](https://github.com/codemirror/CodeMirror/blob/9ec124580735235063c59a8d781ed6e6e498b031/src/util/event.js#L11). Maybe that's why the handler isn't being called when tabs are switched?
  * This [SO answer](https://stackoverflow.com/a/37113763/717341) seems to support that claim.

So what now? Well, reading the [CodeMirror docs](https://codemirror.net/doc/manual.html#api) on the `refresh`-function, it says: 

> If your code does something to change the size of the editor element (window resizes are already listened for), or unhides it, you should probably follow up by calling this method to ensure CodeMirror is still looking as intended. 

Sounds like our use-case. My suggestion is to add a jQuery event-handler for the `resize`-event and then calling `refresh` every time it's triggered. I have tested it and it seems to work.

I'll make a pull-request and be done with this. Running out of beer...

**Comment by selvinortiz** [comment]
@LukasKnuth Seems like your findings are in line with other things I've noticed with the editor as well. For example, live preview sucks right now because the editor does not behave well across browsers due to the way Craft clones content when in preview mode.

This is one of the reasons why I haven't been overly excited to work on Doxter lately, just too many little issues like this that take so much time to get right.

Happy to send you some beer for you work ;)

**Comment by LukasKnuth** [comment]
Yeah, I fucked up a bit with the Github online editor, sorry for the mess. PR should be there now.

@selvinortiz I haven't noticed anything else, but I haven't used the editor much as of yet. Create some issues if you can reproduce stuff, if I have time I'll look at it. I'll add any of my findings as well.
