### ISSUE TITLE
Triple-backticks block seems to be broken on versions > 3.17

### ISSUE THREAD

**Issue by joeforshaw** [selvinortiz/craft-plugin-doxter#18]
Hi there, upgraded my Doxter plugin in my Craft 3.0.9 setup from 3.1.7 to 3.1.9 just before and noticed the multiline code blocks seem to be a bit broke.

Before on 3.1.7:
<img width="1353" alt="screen shot 2018-05-24 at 18 44 11" src="https://user-images.githubusercontent.com/2829655/40502506-190494c2-5f83-11e8-9538-7ff77c73d0ec.png">
Source:
<img width="306" alt="screen shot 2018-05-24 at 18 44 59" src="https://user-images.githubusercontent.com/2829655/40502525-254d6aa6-5f83-11e8-873b-977d3c53b73d.png">

After on 3.1.9:
<img width="1361" alt="screen shot 2018-05-24 at 18 42 45" src="https://user-images.githubusercontent.com/2829655/40502552-361508d0-5f83-11e8-8ce4-679822ffd10a.png">
Source:
<img width="298" alt="screen shot 2018-05-24 at 18 46 28" src="https://user-images.githubusercontent.com/2829655/40502568-405c7436-5f83-11e8-989c-b74e9a62869d.png">

**Comment by selvinortiz** [comment]
@joeforshaw Oh boy! I think I have an idea as to what might be breaking this. I think it has to do with typography styles and the parsing order.

Let me take a look and I'll get back to you.

**Comment by joeforshaw** [comment]
Cool, cheers Selvin!

**Comment by selvinortiz** [comment]
@joeforshaw I just released a new version that fixes the issue you reported https://github.com/selvinortiz/craft-plugin-doxter/releases/tag/3.1.10

`composer update selvinortiz/doxter`

😉
