### ISSUE TITLE
Broken Full Screen Editing (Duplicate)

### ISSUE THREAD

**Issue by selvinortiz** [selvinortiz/craft-plugin-doxter#2]
When clicking on the full-screen button on the editor and the viewport is wide enough for Craft to show its own sidebar, the editor will extend passed/underneath the sidebar.

We should do one of two things:

1. Make sure that the editor fills the full viewport by showing up over the sidebar and any other elements within it.

2. Constraint the editor to the content area, so that clicking on the full-screen button on the editor fills up the content area but leaves the sidebar visible.

<img width="1055" alt="screen shot 2017-04-09 at 8 07 56 pm" src="https://cloud.githubusercontent.com/assets/1922523/24842786/c3d48e12-1d61-11e7-87dd-a2ddb89a4bcd.png">

**Comment by DavidStrada** [comment]
Fixed see [PR](https://github.com/selvinortiz/craft-plugin-doxter/pull/3)

**Comment by selvinortiz** [comment]
@DavidStrada Thank you so much, your PR does indeed, fix the issue👍
