### ISSUE TITLE
Footnotes HTML is double escaped

### ISSUE THREAD

**Issue by rungta** [selvinortiz/craft-plugin-doxter#21]
The following bit of Markdown Extra —

```markdown
Hello[^1].

[^1]: A footnote.
```

results in —

```html
<p>Hello<sup id="fnref1:1"><a href="#fn:1" class="footnote-ref">1</a></sup>.</p>
<div class="footnotes">
<hr />
<ol>
<li id="fn:1">
&lt;p&gt;A footnote.&amp;#160;&lt;a href=&#8221;#fnref1:1&#8221; rev=&#8221;footnote&#8221; class=&#8221;footnote-backref&#8221;&gt;&amp;#8617;&lt;/a&gt;&lt;/p&gt;
</li>
</ol>
</div>
```

**Comment by selvinortiz** [comment]
@rungta Footnotes support in Parsedown (What Doxter is using) is still pretty buggy, but I'll see about looking into it.

**Comment by rungta** [comment]
I tested out the source(s) in the Parsedown Extra dingus http://parsedown.org/extra/ and it _appeared_ to work fine there. And I only noticed this bug on upgrading from Craft 2 to 3. Doxter rendered footnotes just fine in Craft 2.

**Comment by selvinortiz** [comment]
@rungta Got it. A bug in Doxter for Craft 3 then.

I'll try to run some tests as soon as I have a chance.

**Comment by selvinortiz** [comment]
@rungta I did some more digging and I discovered that Parsedown broke footnotes and definition lists a while back and they have not been able to fix it. See https://github.com/erusev/parsedown-extra/issues/118

In the meantime, I replaced Parsedown with Markdown Extra.

I'm not sure that replacing Parsedown with an older parser is the answer but if it's still stable and does not introduce a regression, I know footnotes work and it might be the way to go for now.

Latest changes are in the **dev** branch.

**Comment by rungta** [comment]
> I'm not sure that replacing Parsedown with an older parser is the answer but if it's still stable and does not introduce a regression, I know footnotes work and it might be the way to go for now.

True. Have you considered using the last footnotes compatible version of Parsedown (until they release a fix) instead or switching to Markdown Extra?

**Comment by selvinortiz** [comment]
@rungta I did consider that, however, they broke footnotes due to a security bug introduce by footnote parsing. So, reverting to an old version of Parsedown that supports footnotes would expose Doxter to the issue they patched. That is also the reason they haven't fixed it. There is no way to fix it without re-introducing that security bug or totally refactoring the way the parsing is done.

That's why it's taking so long to fix, as far as I can tell by the threads on GitHub.

**Comment by selvinortiz** [comment]
@rungta After a little more research and experimentation, I ditched Markdown Extra and brought back a *beta* version of Parsedown that fixes the issue with XSS but also addresses footnote parsing.

If you could please test with your specific markdown source, I would really appreciate it.

**Comment by alexagui** [comment]
Thanks! I’m having same issue.  Will test after the holidays.

**Comment by rungta** [comment]
Tested, and footnotes render just fine now! Thanks for fixing this.
