### ISSUE TITLE
Not translatable multi-site field shows HTML instead of source markdown

### ISSUE THREAD

**Issue by rungta** [selvinortiz/craft-plugin-doxter#22]
Steps to reproduce:

1. Start with a regular single site `site_a`.
2. Create a section with a Doxter field.
3. Create a new entry. Add some markdown content to the Doxter field.
4. Add a new site `site_b`.
5. Enable section for the new site `site_b`.
6. Value of the Doxter field in the new `site_b` is HTML. (Value of the entry on the old `site_a` is still markdown at this point of time.)
7. Save the entry.
8. Value of the Doxter field is now HTML on both the new `site_b` and old `site_a` variants of the entry.

Craft 3.0.32
Doxter 3.1.10

**Comment by selvinortiz** [comment]
Wow, that's terrible.

Thanks for the report @rungta.

I'm in the middle of a big transition right now but I'll look into this as soon as I get a chance.
If you're able to track it down, I'd love to accept a PR.

**Comment by selvinortiz** [comment]
@rungta I was able to replicate the issue you reported. Working on a fix!

**Comment by selvinortiz** [comment]
@rungta Should be fixed in the latest release.
