### ISSUE TITLE
Cannot install - composer problem

### ISSUE THREAD

**Issue by piotrpog** [selvinortiz/craft-plugin-doxter#23]
When i try to install plugin, i get this error:
```
Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring. 
Loading composer repositories with package information 
Updating dependencies 
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for selvinortiz/doxter 3.4.7 -> satisfiable by selvinortiz/doxter[3.4.7].
- selvinortiz/doxter 3.4.7 requires erusev/parsedown-extra 0.8.0-beta-1 -> satisfiable by erusev/parsedown-extra[0.8.0-beta-1] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

My system info:
Application Info
PHP version	7.2.2
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.2
Craft edition & version	Craft Solo 3.1.8
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
No plugins are enabled.

**Comment by selvinortiz** [comment]
Hi, yes, unfortunately due to a security issue in a Doxter dependency, I had to realease a version with a beta package to avoid that.

That means that for now, Doxter requires your minimum stability to be set to beta as shown in the install guide here https://selvinortiz.com/plugins/doxter/installation

I'm sorry about this😔

**Comment by piotrpog** [comment]
Thanks for quick reply!
I aded minimum stability setting to `composer.json` and installed it trough console. I guess it cannot be installed trough control panel for now? Because when i tried to install it trough CP, it displayed same error.

**Comment by selvinortiz** [comment]
@piotrpog Odd! Once your package.json file is updated, it should install in both places without any problems. I'll take a look tomorrow and see if I can reproduce that issue.

**Comment by selvinortiz** [comment]
@piotrpog Are you still having this issue? I could not reproduce it locally.
