### ISSUE TITLE
Wrapping content with css class

### ISSUE THREAD

**Issue by piotrpog** [selvinortiz/craft-plugin-doxter#24]
I have question. Is it possible to add css class to spercific paragraph using doxter? I know that it is not possible in regular markdown and markdown extra only allows it for things like headers.

**Comment by selvinortiz** [comment]
@piotrpog You certainly can using a plain html tag, since paragraphs do not have a hook like headers do.

`<p class="my-class">Content...</p>`

The above will work in Doxter.
