### ISSUE TITLE
Example twig code for multi level table of contents

### ISSUE THREAD

**Issue by piotrpog** [selvinortiz/craft-plugin-doxter#25]
Each TOC header has variable `level`. How should such multi level TOC be handled by twig? Can we use Craft `nav` tag?

**Comment by selvinortiz** [comment]
@piotrpog Sorry about the delay.

I'm actually using **TOC** in the [Doxter Docs Sidebar](https://selvinortiz.com/plugins/doxter/installation) but I'm currently just ignoring the `level`.

I supposed it could be used with the `nav tag` but I don't have an example to share.

If you run into any issue implementing the nav you want based on the TOC feature, let me know.
