### ISSUE TITLE
Markdown not being parsed inside custom html tags

### ISSUE THREAD

**Issue by chasegiunta** [selvinortiz/craft-plugin-doxter#26]
@selvinortiz  We're giving Doxter a spin to see if we want to use it on this project, and it's pretty awesome!

We're running into an issue using some custom html tags getting stripped when running through the doxter parser, in our case `<evid>`. It's been our way of doing targeting for styles or using Vue components.

Seems like parsedown is stripping these (rightfully so), but could an option be added to disable the applicable `safeMode` or html escaping?

**Comment by selvinortiz** [comment]
@chasegiunta Would using a custom shortcode work for you?

```
[vue]
  <evid :prop="" @event="handler"></evid>
[/vue]
```

More on Shortcodes: https://selvinortiz.com/plugins/doxter/shortcodes

**Comment by chasegiunta** [comment]
@selvinortiz Thanks for the quick response! Potentially. Are shortcodes unique to Doxter? Is there a shortcode snippet button or anything in the control panel?

Just thinking from a client's perspective, using a html tag seems syntactically easier to write, and in a future scenario where data needed to be exported & moved off Craft and/or Doxter, html tags are non-breaking markdown syntax, as they are supported in any markdown parser.

**Comment by selvinortiz** [comment]
Gotcha!

No, shortcodes are not unique to Doxter and there is no shortcode button in the editor (yet).

You make a good case for having a `safeMode` or `html tag whitelisting`.

To clarify one thing: Did you say that Doxter/Parsedown is doing the stripping? Not Twig, correct?

**Comment by chasegiunta** [comment]
You know what... I totally filed this without doing my due diligence. 🤦‍♂

Since the HTML output was fine without the custom html tags, I assumed they were being stripped.

Turns out they are not! Anything inside of them just isn't being parsed as markdown by the doxter parser. Doing the the normal `md` filter does retain that markdown. 

Can confirm this from doxter/parsedown - but the original issue title is wrong.

**Comment by chasegiunta** [comment]
I'm an idiot. This omission in parsing applies to any html tag.
Is a markdown extra issue apparently. Adding `markdown="1"` to the tag fixes the issue - though I wish there was a way to do this globally. Sorry about this!
