### ISSUE TITLE
Feed Me throwing errors upon importing into Doxter fields

### ISSUE THREAD

**Issue by chasegiunta** [selvinortiz/craft-plugin-doxter#27]
`Call to member function getRaw() on string - DoxterField.php: 107`

```
    public function serializeValue($value, ElementInterface $element = null)
    {
        $value = $value->getRaw();
        $value = StringHelper::encodeMb4($value);

        return $value;
    }
```

**Comment by selvinortiz** [comment]
@chasegiunta My guess is that Feed Me is trying to save plain text and Doxter is not able to wrap the value in its Data object wrapper before `serializing`.

I'll try to take a look at this soon.

Is this a blocker for you currently?

**Comment by chasegiunta** [comment]
It's not. We were able to import into plain text field for the time being.

**Comment by selvinortiz** [comment]
A new fix for this has been released https://github.com/selvinortiz/craft-plugin-doxter/releases/tag/3.4.8
