### ISSUE TITLE
Strip non-alphanumeric and punctuation from headers

### ISSUE THREAD

**Issue by putyourlightson** [selvinortiz/craft-plugin-doxter#28]
The TOC tag strips non-alphanumeric and punctuation using `ElementHelper::createSlug`, however when headers are creating, those characters are not stripped, resulting in TOC links that do not work.

For example: 
```
# Terms & Conditions
```

Results in:
```
TOC: <a href="#terms-conditions">Terms &amp; Conditions</a>

Body: <a class="anchor" href="#terms-amp-conditions" title="Terms &amp; Conditions">#</a>
```

**Comment by selvinortiz** [comment]
Thank you, Ben. I'll take a look this week!
