### ISSUE TITLE
Disable typographic hyphenation

### ISSUE THREAD

**Issue by putyourlightson** [selvinortiz/craft-plugin-doxter#29]
If the `addTypographyStyles` setting is enabled then hyphenation will automatically be enabled. Since we can handle hyphenation in CSS directly and with more control, I'd like to suggest disabling it:

    $settings->set_hyphenation(false);

https://github.com/selvinortiz/craft-plugin-doxter/blob/3.4.8/src/common/parsers/Typography.php#L26

The advantage of this is that we can continue using typography styles but can decide what tags should be hyphenated using CSS. Is this something you might consider changing, or at least making configurable?

**Comment by putyourlightson** [comment]
Never mind, I just realised I can still override hyphenation for specific tags using CSS. Thanks Selvin!

**Comment by putyourlightson** [comment]
Reopening because I still think there's a case to be made for disabling hyphenation. Even if overriding using the `hyphens: none;` CSS property, copy-pasting the text into a text editor results in hyphenated text, for example:

```
Blitz provides intel-li-gent stat-ic page cach-ing for cre-at-ing light-ning-fast sites with Craft CMS. It sig-ni-fic-antly improves a site’s per-form-ance by redu-cing serv-er response time. 
```

**Comment by putyourlightson** [comment]
Since the `hyphens` property is not supported across the board, it would probaby better to make it a config setting. 
https://caniuse.com/#feat=css-hyphens

Let me know if you'd like a pull request for this as I need it for a current project :)

**Comment by selvinortiz** [comment]
Ben, a pull request would be most welcomed👌
