### ISSUE TITLE
Certain combinations of settings options break functionality

### ISSUE THREAD

**Issue by jsunsawyer** [selvinortiz/craft-plugin-doxter#35]
Using the following markup:
```
# 1st level heading
## 2nd level heading
### 3rd level heading
```

The following combination of settings...
![Screen Shot 2020-02-07 at 10 52 12 AM](https://user-images.githubusercontent.com/1007191/74057037-eb9c4d80-4997-11ea-8e65-5cf4249d4fde.png)

results in...
```
<h1>1st level heading</h1>
<h2>2nd level heading</h2>
<h3>3rd level heading</h3>
```

---

Enabling only `h1` as the only checked setting in `Which headers do you want to make linkable by default?` with the same markup results in...
```
<h2 id="1st-level-heading">1st level heading <a class="anchor" href="#1st-level-heading" title="1st level heading">#</a></h2>
<h2>2nd level heading</h2>
<h3>3rd level heading</h3>
```

Notice how it starts with an `h2` (as expected), but renders the following tag also as an `h2`, and also improperly links the starting `h2` when it should only be linked if it's an `h1`.

---

There are various buggy combinations that I've found. Hope this helps as a starting point.

Craft: 3.4.4.1
Doxter: 3.4.9

**Comment by engram-design** [comment]
I can't seem to replicate this on [4.0.0](https://github.com/verbb/doxter/releases/tag/4.0.0) with your exact setup. Can you let me know if there's any more buggy combinations?
