### ISSUE TITLE
Nested ordered lists start at incorrect value

### ISSUE THREAD

**Issue by jsunsawyer** [selvinortiz/craft-plugin-doxter#37]
In an ordered list with a nested ordered list placed after the first list item, an `ol` tag with `start="2"` is added.

![Screen Shot 2020-02-07 at 2 32 41 PM](https://user-images.githubusercontent.com/1007191/74070741-ba7f4580-49b6-11ea-9c88-093f5dab8f34.png)

Craft: 3.4.4.1
Doxter: 3.4.9

**Comment by jsunsawyer** [comment]
^ To avoid any confusion, the **2. Use License** is a heading tag.

**Comment by selvinortiz** [comment]
@jsunsawyer Would you mind sharing the exact markdown content and the rendered output, so that I can reproduce it in my testing environment?

**Comment by jsunsawyer** [comment]
@selvinortiz I could have explained this better. It's not that the markdown is rendering content incorrectly, it's that tabbing list items when creating nested lists increments the list count.

1. Set up a new ordered list
2. Create a few items
3. Use tab to indent the list (expected result is to change the list count to 1 (or alphanumeric, then roman, etc. as lists nest further)

You'll notice that you end up with something like.

```
1. First list item
2. Second list item
  3. First nested list item (this should start at 1.)
4. Third main list item (this should start at 3.)
```

Maybe it's just that this isn't accounted for and must be done manually. If that's the case, it'd be nice if this could be handled automatically by doxter.

**Comment by selvinortiz** [comment]
It seems like Parsedown and ParsedownExtra are starting to lag quite a bit in terms of support for GFM and speed. I'm considering falling back to `cebe/markdown`, which Yii and Craft use under the hood

**Comment by selvinortiz** [comment]
@jsunsawyer In further testing, it looks like all parsers have edge case issues with nested lists depending on the spacing used. See https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#nested-lists

Adjusting your spacing for nested list items should yield the correct rendered output.

Please re-open if that's not the case for you.

**Comment by jsunsawyer** [comment]
@selvinortiz Ooops, initially responded as if this was another issue.

I've adjusted my spacing in various ways and the values are incorrect (both in the CP and front-end of my site).

Are you able to produce the correct nested values in the CP?

**Comment by selvinortiz** [comment]
@jsunsawyer When you say _you've updated your spacing in various ways_, do you mean manually or via the field  settings?

<img width="516" alt="Screen Shot 2020-02-28 at 12 20 56 PM" src="https://user-images.githubusercontent.com/1922523/75574966-dc537180-5a24-11ea-8996-7e9cf5708f33.png">

**Comment by jsunsawyer** [comment]
@selvinortiz I'm unable to get the proper display of nested lists with any sort of spacing. I tried all kinds of tab lengths manually, and just tested with `Tab Size` set to 4.

My result in the CP is...
```
1. test
    2. test
        3. test
```
The source for this is...
```
<div class="CodeMirror-code" style=""><pre class=" CodeMirror-line "><span style="padding-right: 0.1px;"><span class="cm-formatting cm-formatting-list cm-formatting-list-ol cm-variable-2 CodeMirror-selectedtext">1. </span><span class="cm-variable-2 CodeMirror-selectedtext">test</span></span></pre><pre class=" CodeMirror-line "><span style="padding-right: 0.1px;"><span class=" CodeMirror-selectedtext"> &nbsp;  </span><span class="cm-formatting cm-formatting-list cm-formatting-list-ol cm-variable-3 CodeMirror-selectedtext">2. </span><span class="cm-variable-3 CodeMirror-selectedtext">test</span></span></pre><pre class=" CodeMirror-line "><span style="padding-right: 0.1px;"><span class=" CodeMirror-selectedtext"> &nbsp; &nbsp; &nbsp;  </span><span class="cm-formatting cm-formatting-list cm-formatting-list-ol cm-keyword CodeMirror-selectedtext">3. </span><span class="cm-keyword CodeMirror-selectedtext">test</span></span></pre>
```
The front-end output is...
```
<ol>
<li>test
<ol start="2">
<li>test
<ol start="3">
<li>test</li>
</ol></li>
</ol></li>
</ol>
```

**Comment by selvinortiz** [comment]
@jsunsawyer I know it's been a long while and I'm not sure you're still using Doxter, but I just pushed a long awaited release that replaced the old markdown parser (Parsedown) with the one used by Craft.

Would love it if you could run your tests again and let me know if the issues listed above persists.
