### ISSUE TITLE
Asset reference tag does nothing

### ISSUE THREAD

**Issue by piotrpog** [selvinortiz/craft-plugin-doxter#38]
Well, maybe i am doing something wrong. But I noticed that when i put asset reference tag into markdown text, i end with something like that: `{asset:5}`. 

When i use `parseRefs` filter in twig template, this reference tag is not compiled to anything. When i manually change it to `{asset:5:url}`, url of asset is outputted, so I can tell that refence tags are working. 

Ideally, it would be if `<img>` tag was outputted. I tried using `{asset:5:getImg()}`, but it didnt worked. Maybe doxter should output reference tags like this?

```
![]({asset:5:url})
```

**Comment by chadcrowell** [comment]
Have you tried the [image shortcode](https://selvinortiz.com/plugins/doxter/shortcodes#image-shortcode)?

Be sure to turn on shortcode parsing in the plugin settings.

**Comment by engram-design** [comment]
Can't reproduce this, sorry!
