### ISSUE TITLE
Linked Hash/pound symbol showing up out of nowhere?

### ISSUE THREAD

**Issue by chadcrowell** [selvinortiz/craft-plugin-doxter#39]
I love Doxter, and have been building a site with it for a few months. I recently started implementing shortcakes, which is SO awesome. When I did that, I changed that field rendering in the template from `{{ field|md }}` to `{{ field|doxter }}`. At that point I realized I should probably change all the |md filters to |doxter in order to take advantage of everything Doxter offers.

The issue is that, now, on some iterations of some fields, I get a linked hash/pound sign that I don't know where it comes from. [Look at this page for instance](https://www.gcx.dev/products/series/vhm-series/vhm-t#configurations) - the first text block has them. They don't exist in the content, not even as hidden symbols from pasted text. Here is the field that drives that content: https://d.pr/i/IzJORg

If I change the filter back to |md, the hash marks go away. Any idea what is going on here and how to fix it?

Craft 3.5.15.1
Doxter 3.5.1

**Comment by selvinortiz** [comment]
@chadcrowell When using Doxter as a filter, you may have to pass in **options** to disable certain features, like _parsing headers anchors_.

Take a look at this doc (https://selvinortiz.com/plugins/doxter/parsing-options#parsing-filter-doxter) for more on that and if it isn't helpful, I'd be happy to help you further.

The linked hashes come from Doxter parsing headers and creating anchors for them.

**Comment by selvinortiz** [comment]
For brevity, here is what to do to disable linked hashes.

```
md|doxter({ addHeaderAnchors: false })
```

**Comment by chadcrowell** [comment]
Ah! Thank you so much. I probably would have found that eventually lol...

I'll make it a feature request then... maybe we could define a standard set of options in the doxter.php config file that get applied to all doxter filters? That might be nice for situations like this. 

Thanks again.

**Comment by chadcrowell** [comment]
Oh - looks like I can already turn that off in the plugin settings. Nevermind!
