### ISSUE TITLE
After update replace to new Doxter plugin

### ISSUE THREAD

**Issue by aanimation** [selvinortiz/craft-plugin-doxter#47]
### Describe the bug

Hi,

im a web developer and using craft-cms for a lot of project, one of them was using Doxter. after got announce to get update Doxter by run `composer require verbb/doxter && composer remove selvinortiz/doxter`.

so far the update ran good. Until ive tried to open an entry which one doxter field within. one-by-one open the entry. and got this error ```Cannot declare class verbb\doxter\models\Shortcode because the name is already in use```.

Has anyone experienced this too? and pls help how to fix it

screenshoot shared on https://paste.pics/HTYIU

### Steps to reproduce

1. composer update from Craft CMS 3.6.17 to get latest one Craft CMS 3.7.50
2. finish up config change
3. composer require verbb/doxter && composer remove selvinortiz/doxter
4. finish up until got the new Doxter

### Craft CMS version

3.7.50

### Plugin version

4.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [4.0.1](https://github.com/verbb/doxter/releases/tag/4.0.1)

**Comment by aanimation** [comment]
thanks @engram-design solved now
