### ISSUE TITLE
Shortcode::parseAttributes() must be of the type array, string returned

### ISSUE THREAD

**Issue by aanimation** [selvinortiz/craft-plugin-doxter#48]
### Describe the bug

Hi,
In another section, found a bug `Shortcode::parseAttributes() must be of the type array, string returned`
Please help

https://paste.pics/HUC5M

### Steps to reproduce

1. 
2. 

### Craft CMS version

3.7.50

### Plugin version

4.0.1

### Multi-site?

No

**Comment by aanimation** [comment]
i have tried to debug,

this line `$attributes = ltrim($text);` is string

worked if changed to `$attributes = [ltrim($text)];`

OR

`$attributes[] = ltrim($text);`

**Comment by engram-design** [comment]
This was fixed for Craft 4, but back-tracking this to Craft 3 in [4.0.2](https://github.com/verbb/doxter/releases/tag/4.0.2)
