### ISSUE TITLE
Show Toolbar Not Working Unless All Options Selected

### ISSUE THREAD

**Issue by 0xgdr** [selvinortiz/craft-plugin-doxter#50]
### Describe the bug

I am wanting to deselect some toolbar options for the WYSIWYG. Unless they are all selected the toolbar will not show.

### Steps to reproduce

1. Create a Doxter field
2. Set display toolbar to true
3. Remove some options from the list (Users, Tags).
4. Save the field and assign to an entry
5. The entry will not display the tool bar for the WYSIWYG.
6. Select all the options for the toolbar
7. The WYSIWYG will display.

### Craft CMS version

4.3.6

### Plugin version

latest

### Multi-site?

Yes

### Additional context

The field is translatable on a multi site.

**Comment by engram-design** [comment]
Fixed in [5.0.3](https://github.com/verbb/doxter/releases/tag/5.0.3)
