### ISSUE TITLE
parseRefs bug in 3.1.0

### ISSUE THREAD

**Issue by mikestecker** [selvinortiz/craft-plugin-doxter#6]
After updating to 3.1.0 and going to edit an existing entry with a Doxter field, I get the following error:

`Argument 1 passed to craft\services\Elements::parseRefs() must be of the type string called in site/vendor/selvinortiz/doxter/src/common/parsers/ReferenceTag.php on line 28`

**Comment by selvinortiz** [comment]
Thank you Mike, we'll look into this ASAP

**Comment by gui-gui** [comment]
Hi @mikestecker , 

I'm having a tough time trying to reproduce this error in my end. Would you be ok sharing the content of the doxter field that is triggering this error?  _(if you prefer to share it privately, i'm @gui-gui in craft's slack)._

**Comment by mikestecker** [comment]
I don't think it's related to any specific content, because it happens when I try and make a new entry as well.

I'd hate to have to remove the plugin and reinstall because I'd have to recreate my fields as well... Is there any other information I might be able to share instead?

You can find me on the Slack group too: @mikestecker
